apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgresql-dev
  namespace: {{ .Values.projectName }}-bdd-dev
spec:
  version: "10.2-v1"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
  terminationPolicy: WipeOut