apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: {{ .Values.projectName }}-pgadmin-dev
  namespace: {{ .Values.projectName }}-bdd-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        name: {{ .Values.projectName }}-pgadmin-dev
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        - name: PGADMIN_PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: {{ .Values.projectName }}-pgadmin-dev
  namespace: {{ .Values.projectName }}-bdd-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin
  type: LoadBalancer